### ISSUE TITLE
screens

### ISSUE THREAD

**Issue by pilot** [lazy-ants/remote-manager#9]

**Comment by pilot** [comment]
<img width="672" alt="image" src="https://user-images.githubusercontent.com/28564/81734095-ac503200-949b-11ea-90fc-1a7a7803aff5.png">

**Comment by lazyants** [comment]
![ls](https://user-images.githubusercontent.com/249065/81821048-b6bd0b00-9531-11ea-93a7-e58422c77b2b.png)
![upgrade](https://user-images.githubusercontent.com/249065/81821055-b91f6500-9531-11ea-8480-722a2cc65fbe.png)
![system-info](https://user-images.githubusercontent.com/249065/81821061-ba509200-9531-11ea-8829-0fb9ca619105.png)
![validate](https://user-images.githubusercontent.com/249065/81821063-ba509200-9531-11ea-85eb-ef735ab42f1f.png)
![uptime](https://user-images.githubusercontent.com/249065/81821064-bae92880-9531-11ea-989d-e64e5eff0ac7.png)
![reboot](https://user-images.githubusercontent.com/249065/81821065-bae92880-9531-11ea-9b70-59d6d8d941d1.png)
![os](https://user-images.githubusercontent.com/249065/81821066-bb81bf00-9531-11ea-93be-cdd89c1b5f3a.png)
![kernel](https://user-images.githubusercontent.com/249065/81821068-bb81bf00-9531-11ea-916a-02daef2b77f4.png)
![docker-ps](https://user-images.githubusercontent.com/249065/81821072-bcb2ec00-9531-11ea-8fd6-51513f406ab1.png)
![docker-prune](https://user-images.githubusercontent.com/249065/81821073-bd4b8280-9531-11ea-940d-cff7a7cd0c61.png)
![docker-compose](https://user-images.githubusercontent.com/249065/81821076-bd4b8280-9531-11ea-8a7f-3f5bbf1418bd.png)

**Comment by lazyants** [comment]
![ufw](https://user-images.githubusercontent.com/249065/82075698-f116db80-96dc-11ea-8fa4-94960b5fc44e.png)
